const para = [
    
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras libero magna, molestie ac posuere vitae, mattis at sapien. Nulla maximus justo vel mi fringilla viverra. In dignissim in mauris pulvinar rhoncus. Suspendisse maximus risus sit amet dolor auctor faucibus. Nunc nisl turpis, sagittis id diam sit amet, malesuada accumsan enim. Proin sit amet arcu vitae quam pharetra malesuada posuere tristique lacus. Nullam eu vulputate felis, eget fringilla massa. Nulla sed condimentum turpis, vel fermentum neque. In et quam in dui placerat venenatis. Etiam risus nisl, rutrum sed purus id, auctor venenatis erat. Integer sagittis congue enim. Aenean ut suscipit tellus, luctus efficitur enim. Quisque a leo lorem. Vestibulum non nisl pellentesque, mattis ipsum in, posuere ante. Sed consectetur aliquet risus id mattis. Nulla vitae porttitor est. Curabitur ac dolor pretium, laoreet neque at, consectetur risus.",
"Etiam vitae euismod nulla, non feugiat nunc. Donec ut quam id nisi ornare viverra. Nunc efficitur augue vel tempor gravida. Sed vitae arcu vestibulum, vestibulum elit ut, tristique tortor. Nam ut varius ligula. Suspendisse sem erat, pulvinar quis urna sed, tempus dapibus ex. Praesent ut ante consequat, ultrices urna non, sodales sapien. Quisque in ligula faucibus, pretium nunc eu, ullamcorper tortor. In imperdiet vehicula sapien, ac iaculis augue cursus eget. Cras sit amet ligula eros.",
"Fusce gravida leo non urna viverra molestie. Ut condimentum ante a velit molestie tempus. Praesent eu sapien in est porta tincidunt in vel nisi. Vestibulum venenatis, nisi sit amet ornare vestibulum, arcu tellus sollicitudin nulla, ac lobortis lectus ex quis massa. Maecenas scelerisque leo et quam aliquet placerat. Fusce convallis sem ac felis condimentum, et finibus purus molestie. Aliquam vitae mattis dui. Vivamus euismod enim ut sem faucibus, in maximus quam mollis. Praesent placerat semper semper. Etiam dolor mauris, egestas non commodo vitae, tincidunt vitae enim. Nulla facilisi. Duis interdum hendrerit lectus, non eleifend orci rutrum eget.",
"Nulla vestibulum odio sed urna interdum lacinia. Pellentesque ut justo leo. Quisque congue id velit sed aliquam. Praesent tempus diam mauris, sit amet convallis nibh scelerisque sit amet. Proin mattis, nibh vel hendrerit molestie, odio tortor consequat justo, eu fermentum ante augue eu mauris. Donec tempor, velit non rhoncus commodo, enim mi posuere purus, et congue ipsum mauris sed augue. Sed sollicitudin nisl vel diam dapibus, rhoncus aliquet tortor convallis. Fusce massa enim, imperdiet non purus vel, luctus auctor dolor. Curabitur vel cursus ex. Aliquam erat volutpat. Nunc scelerisque mauris vitae placerat porttitor.",
"Pellentesque ut purus semper, tempor eros eu, consequat nisi. Maecenas quis consequat ligula, non sagittis lorem. Integer commodo porta ante eget cursus. Sed finibus in magna eget egestas. Aliquam ut leo sit amet ante euismod consectetur eget a velit. Aenean ipsum nisi, iaculis ut tristique vel, pharetra sed sapien. Cras placerat purus fermentum sem lobortis interdum eu sollicitudin dui. Ut vehicula magna massa, eu efficitur arcu sagittis ut. Cras bibendum sem non dui vestibulum laoreet. Suspendisse est libero, luctus ut imperdiet ac, porta tincidunt mi. Aliquam placerat vehicula metus, in pellentesque quam vehicula vitae. Donec cursus magna porta, volutpat libero ut, laoreet justo. Ut tristique orci at sem sodales aliquet. Ut vitae mollis leo, nec gravida metus. Etiam ornare, nisl vitae gravida fermentum, tortor nisi eleifend nibh, eget ornare dui diam a ante. Curabitur eros dolor, convallis a gravida sit amet, malesuada eu ante.",
"Proin leo dolor, dictum sit amet efficitur id, dignissim vel odio. Cras ac ipsum sit amet augue placerat malesuada. Sed turpis mi, accumsan at blandit ac, condimentum vitae felis. Vivamus vitae vulputate dui. Donec quis faucibus enim. Nullam vel ex feugiat, mattis leo at, bibendum libero. Vestibulum in sapien congue dui scelerisque tristique eu eu velit.",
"Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur vulputate purus sapien, id consequat tortor ullamcorper vel. Sed elementum urna a enim congue, et aliquam libero ornare. Mauris vel est urna. Maecenas ultrices blandit velit, nec dignissim leo vehicula eget. Nullam consectetur eros sem, vitae iaculis enim dignissim vitae. Suspendisse non dignissim neque.",
"Pellentesque pellentesque nisl in velit eleifend, eget pretium felis dignissim. Donec auctor sem non metus ornare, quis suscipit augue sagittis. Etiam nec lacus vitae velit interdum aliquet vitae at nulla. Duis eget pulvinar tellus. Phasellus ullamcorper molestie augue id efficitur. Nulla tincidunt purus et odio varius, non lacinia enim egestas. Proin id elit sem. Donec in tempor lacus, vel convallis neque. Aenean sed consequat felis. Pellentesque ex felis, dapibus quis lacus sed, scelerisque placerat diam. Proin vitae tempor lacus. Nunc dictum sem a scelerisque fringilla. Aenean dignissim ligula vitae elit ultricies auctor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam ullamcorper consequat tellus, ac rhoncus libero viverra at.",
"Nunc vitae varius ante. Integer facilisis orci augue, eu hendrerit justo porta a. Suspendisse imperdiet metus eu pharetra consequat. Curabitur posuere mauris mauris, ut condimentum nunc imperdiet eget. Donec elementum venenatis nibh, quis accumsan augue blandit id. Nulla aliquam ornare magna, eget cursus justo suscipit sit amet. Donec a ipsum dictum, suscipit risus id, mollis metus."

]

export default para